# Generated by Django 3.0.5 on 2020-05-29 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolUsuario', models.CharField(max_length=50, unique=True, verbose_name='Rol Usuario')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('usuarioRegistra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realiza el registro')),
            ],
            options={
                'verbose_name': 'RolUsuario',
                'verbose_name_plural': 'RolesUsuario',
                'ordering': ['id'],
            },
        ),
    ]
