# Generated by Django 3.0.5 on 2020-05-30 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baliza', '0002_auto_20200529_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='braceletumbrals',
            options={'ordering': ['id'], 'verbose_name': 'Bracele tUmbral', 'verbose_name_plural': 'Bracelet Umbrales'},
        ),
    ]
