# Generated by Django 3.0.5 on 2020-05-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliza', '0003_auto_20200529_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='indHabilitado',
            field=models.BooleanField(default=True, verbose_name='Indicador Habilitado'),
        ),
        migrations.AlterField(
            model_name='baliza',
            name='indHabilitado',
            field=models.BooleanField(default=True, verbose_name='Indicador Habilitado'),
        ),
        migrations.AlterField(
            model_name='bracelet',
            name='indHabilitado',
            field=models.BooleanField(default=True, verbose_name='Indicador Habilitado'),
        ),
        migrations.AlterField(
            model_name='instalacionbaliza',
            name='indHabilitado',
            field=models.BooleanField(default=True, verbose_name='Indicador Habilitado'),
        ),
        migrations.AlterField(
            model_name='piso',
            name='indHabilitado',
            field=models.BooleanField(default=True, verbose_name='Indicador Habilitado'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='indHabilitado',
            field=models.BooleanField(default=True, verbose_name='Indicador Habilitado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='indHabilitado',
            field=models.BooleanField(default=True, verbose_name='Indicador Habilitado'),
        ),
    ]
