# Generated by Django 3.0.5 on 2020-05-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliza', '0004_auto_20200529_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piso',
            name='piso',
            field=models.CharField(max_length=50, verbose_name='Piso'),
        ),
    ]
