# Generated by Django 3.0.5 on 2020-05-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliza', '0006_auto_20200529_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialubicacion',
            name='fechaSalidaArea',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Salida Area'),
        ),
    ]
