# Generated by Django 3.0.5 on 2020-05-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliza', '0007_auto_20200529_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialbraceletsensors',
            name='nivel_bateria',
            field=models.PositiveIntegerField(max_length=100, verbose_name='Porcentaje nivel Bateria'),
        ),
        migrations.AlterField(
            model_name='historialbraceletsensors',
            name='proximidad_sensor',
            field=models.BooleanField(default=True, verbose_name='Sensor proximidad para detectar ManillaPuesta en la persona'),
        ),
    ]
