# Generated by Django 3.0.5 on 2020-06-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baliza', '0008_auto_20200529_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='braceletpatienhospital',
            options={'ordering': ['id'], 'verbose_name': 'Bracelet Patien Hospital', 'verbose_name_plural': 'Bracelet Patiens Hospital'},
        ),
        migrations.AlterModelOptions(
            name='historialbraceletsensors',
            options={'ordering': ['id'], 'verbose_name': 'Historial Bracelet Sensors', 'verbose_name_plural': 'Historials Bracelet Sensors'},
        ),
        migrations.AlterModelOptions(
            name='historialubicacion',
            options={'ordering': ['id'], 'verbose_name': 'Historial Ubicacion', 'verbose_name_plural': 'Historial Ubicaciones'},
        ),
        migrations.AlterModelOptions(
            name='rolusuario',
            options={'ordering': ['id'], 'verbose_name': 'Rol Usuario', 'verbose_name_plural': 'Roles Usuario'},
        ),
        migrations.AlterField(
            model_name='historialbraceletsensors',
            name='nivel_bateria',
            field=models.PositiveIntegerField(verbose_name='Porcentaje nivel Bateria'),
        ),
    ]
